/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finanace_tracker;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import loginandsignup.ValidateData;

/**
 *
 * @author Tharusha
 */
public class EditUserDetails extends javax.swing.JFrame {

    /**
     * Creates new form EditUserDetails
     */
    public EditUserDetails() {
        initComponents();
        
        //setting password hide character
        editPassword.setEchoChar('\u25cf');
        editPasswordConf.setEchoChar('\u25cf');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        signUpEmail = new javax.swing.JTextField();
        signUpPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        signUpPasswordConf = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        signInRedirectButton = new javax.swing.JButton();
        fNameLbl = new javax.swing.JLabel();
        lNameLbl = new javax.swing.JLabel();
        signUpEmailLbl = new javax.swing.JLabel();
        signUpPasswordLbl = new javax.swing.JLabel();
        signUpPassConfLbl = new javax.swing.JLabel();
        noticeLbl = new javax.swing.JLabel();
        passConfToggleButton = new javax.swing.JToggleButton();
        passToggleButton = new javax.swing.JToggleButton();
        closeButton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editFname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        editLname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editEmail = new javax.swing.JTextField();
        editPassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        editPasswordConf = new javax.swing.JPasswordField();
        saveEditBtn = new javax.swing.JButton();
        eFNameLbl = new javax.swing.JLabel();
        eLNameLbl = new javax.swing.JLabel();
        eEmailLbl = new javax.swing.JLabel();
        ePasswordLbl = new javax.swing.JLabel();
        ePassConfLbl = new javax.swing.JLabel();
        eNoticeLbl = new javax.swing.JLabel();
        editPassConfToggleButton = new javax.swing.JToggleButton();
        editPassToggleButton = new javax.swing.JToggleButton();
        eCloseButton = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Sign Up");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("First Name");

        firstName.setBackground(new java.awt.Color(255, 255, 255));
        firstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstName.setForeground(new java.awt.Color(0, 0, 0));
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameKeyPressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Last Name");

        lastName.setBackground(new java.awt.Color(255, 255, 255));
        lastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastName.setForeground(new java.awt.Color(0, 0, 0));
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameKeyPressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email");

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password");

        signUpEmail.setBackground(new java.awt.Color(255, 255, 255));
        signUpEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signUpEmail.setForeground(new java.awt.Color(0, 0, 0));
        signUpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpEmailActionPerformed(evt);
            }
        });
        signUpEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signUpEmailKeyPressed(evt);
            }
        });

        signUpPassword.setBackground(new java.awt.Color(255, 255, 255));
        signUpPassword.setForeground(new java.awt.Color(0, 0, 0));
        signUpPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpPasswordActionPerformed(evt);
            }
        });
        signUpPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signUpPasswordKeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Confirm Password");

        signUpPasswordConf.setBackground(new java.awt.Color(255, 255, 255));
        signUpPasswordConf.setForeground(new java.awt.Color(0, 0, 0));
        signUpPasswordConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpPasswordConfActionPerformed(evt);
            }
        });
        signUpPasswordConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signUpPasswordConfKeyPressed(evt);
            }
        });

        signUpButton.setBackground(new java.awt.Color(0, 102, 102));
        signUpButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        signInRedirectButton.setBackground(new java.awt.Color(255, 255, 255));
        signInRedirectButton.setForeground(new java.awt.Color(255, 51, 51));
        signInRedirectButton.setText("Back");
        signInRedirectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInRedirectButtonActionPerformed(evt);
            }
        });

        fNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        fNameLbl.setForeground(new java.awt.Color(255, 0, 0));

        lNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        lNameLbl.setForeground(new java.awt.Color(255, 0, 0));

        signUpEmailLbl.setBackground(new java.awt.Color(255, 255, 255));
        signUpEmailLbl.setForeground(new java.awt.Color(255, 0, 0));

        signUpPasswordLbl.setBackground(new java.awt.Color(255, 255, 255));
        signUpPasswordLbl.setForeground(new java.awt.Color(255, 0, 0));

        signUpPassConfLbl.setBackground(new java.awt.Color(255, 255, 255));
        signUpPassConfLbl.setForeground(new java.awt.Color(255, 0, 0));

        noticeLbl.setBackground(new java.awt.Color(255, 255, 255));
        noticeLbl.setForeground(new java.awt.Color(255, 0, 0));

        passConfToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        passConfToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/eye-line.png"))); // NOI18N
        passConfToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passConfToggleButtonMouseClicked(evt);
            }
        });
        passConfToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passConfToggleButtonActionPerformed(evt);
            }
        });

        passToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        passToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/eye-line.png"))); // NOI18N
        passToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passToggleButtonMouseClicked(evt);
            }
        });
        passToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passToggleButtonActionPerformed(evt);
            }
        });

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross (2).png"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(noticeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(101, 101, 101)
                        .addComponent(closeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signInRedirectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(signUpEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(signUpPasswordConf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(signUpPassword, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passConfToggleButton)
                                    .addComponent(passToggleButton))))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(signUpEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(signUpPasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(signUpPassConfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addComponent(closeButton))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signUpEmailLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpPassword)
                    .addComponent(signUpPasswordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpPassConfLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signUpPasswordConf)
                    .addComponent(passConfToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(noticeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInRedirectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setText("Edit Profile");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("First Name");

        editFname.setBackground(new java.awt.Color(255, 255, 255));
        editFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editFname.setForeground(new java.awt.Color(0, 0, 0));
        editFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFnameActionPerformed(evt);
            }
        });
        editFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editFnameKeyPressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Last Name");

        editLname.setBackground(new java.awt.Color(255, 255, 255));
        editLname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editLname.setForeground(new java.awt.Color(0, 0, 0));
        editLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLnameActionPerformed(evt);
            }
        });
        editLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editLnameKeyPressed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Password");

        editEmail.setBackground(new java.awt.Color(255, 255, 255));
        editEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editEmail.setForeground(new java.awt.Color(0, 0, 0));
        editEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmailActionPerformed(evt);
            }
        });
        editEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editEmailKeyPressed(evt);
            }
        });

        editPassword.setBackground(new java.awt.Color(255, 255, 255));
        editPassword.setForeground(new java.awt.Color(0, 0, 0));
        editPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordActionPerformed(evt);
            }
        });
        editPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editPasswordKeyPressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Confirm Password");

        editPasswordConf.setBackground(new java.awt.Color(255, 255, 255));
        editPasswordConf.setForeground(new java.awt.Color(0, 0, 0));
        editPasswordConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordConfActionPerformed(evt);
            }
        });
        editPasswordConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editPasswordConfKeyPressed(evt);
            }
        });

        saveEditBtn.setBackground(new java.awt.Color(102, 0, 153));
        saveEditBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveEditBtn.setText("Save");
        saveEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditBtnActionPerformed(evt);
            }
        });

        eFNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        eFNameLbl.setForeground(new java.awt.Color(255, 0, 0));

        eLNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        eLNameLbl.setForeground(new java.awt.Color(255, 0, 0));

        eEmailLbl.setBackground(new java.awt.Color(255, 255, 255));
        eEmailLbl.setForeground(new java.awt.Color(255, 0, 0));

        ePasswordLbl.setBackground(new java.awt.Color(255, 255, 255));
        ePasswordLbl.setForeground(new java.awt.Color(255, 0, 0));

        ePassConfLbl.setBackground(new java.awt.Color(255, 255, 255));
        ePassConfLbl.setForeground(new java.awt.Color(255, 0, 0));

        eNoticeLbl.setBackground(new java.awt.Color(255, 255, 255));
        eNoticeLbl.setForeground(new java.awt.Color(255, 0, 0));

        editPassConfToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        editPassConfToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/eye-line.png"))); // NOI18N
        editPassConfToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPassConfToggleButtonMouseClicked(evt);
            }
        });
        editPassConfToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPassConfToggleButtonActionPerformed(evt);
            }
        });

        editPassToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        editPassToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/eye-line.png"))); // NOI18N
        editPassToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPassToggleButtonMouseClicked(evt);
            }
        });
        editPassToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPassToggleButtonActionPerformed(evt);
            }
        });

        eCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross (2).png"))); // NOI18N
        eCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eCloseButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(eNoticeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(94, 94, 94)
                        .addComponent(eCloseButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editLname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editFname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editPasswordConf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(editPassword, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editPassConfToggleButton)
                                    .addComponent(editPassToggleButton)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eLNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eFNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ePasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ePassConfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(eCloseButton)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editFname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eFNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eLNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editLname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eEmailLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editPassword)
                    .addComponent(ePasswordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editPassToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ePassConfLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editPasswordConf)
                    .addComponent(editPassConfToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(eNoticeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void firstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_firstNameKeyPressed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void lastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameKeyPressed

    private void signUpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpEmailActionPerformed

    private void signUpEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signUpEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpEmailKeyPressed

    private void signUpPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpPasswordActionPerformed

    private void signUpPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signUpPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpPasswordKeyPressed

    private void signUpPasswordConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpPasswordConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpPasswordConfActionPerformed

    private void signUpPasswordConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signUpPasswordConfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpPasswordConfKeyPressed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void signInRedirectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInRedirectButtonActionPerformed

    }//GEN-LAST:event_signInRedirectButtonActionPerformed

    private void passConfToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passConfToggleButtonMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_passConfToggleButtonMouseClicked

    private void passConfToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passConfToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passConfToggleButtonActionPerformed

    private void passToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passToggleButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passToggleButtonMouseClicked

    private void passToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passToggleButtonActionPerformed

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void editFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFnameActionPerformed

    private void editFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editFnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        editLname.requestFocus();
    }//GEN-LAST:event_editFnameKeyPressed

    private void editLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editLnameActionPerformed

    private void editLnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editLnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        editEmail.requestFocus();
    }//GEN-LAST:event_editLnameKeyPressed

    private void editEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmailActionPerformed

    private void editEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editEmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        editPassword.requestFocus();
    }//GEN-LAST:event_editEmailKeyPressed

    private void editPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPasswordActionPerformed

    private void editPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        editPasswordConf.requestFocus();
    }//GEN-LAST:event_editPasswordKeyPressed

    private void editPasswordConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPasswordConfActionPerformed

    private void editPasswordConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPasswordConfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            saveActionPerformer();
        }
    }//GEN-LAST:event_editPasswordConfKeyPressed

    private void saveEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditBtnActionPerformed
        // TODO add your handling code here:
        saveActionPerformer();
    }//GEN-LAST:event_saveEditBtnActionPerformed
    
    //'?' and label remover
    private void eEmptySymbolRemover(){
            eFNameLbl.setText("");
            eLNameLbl.setText("");
            eEmailLbl.setText("");
            ePasswordLbl.setText("");
            ePassConfLbl.setText("");
            eNoticeLbl.setText("");
    }
    
    //This method is used to perform the sign up procedure
    private void saveActionPerformer(){
        if(editFname.getText().trim().isEmpty() && (editLname.getText().trim().isEmpty()) && (editEmail.getText().trim().isEmpty()) && (editPassword.getText().trim().isEmpty()) && (editPasswordConf.getText().trim().isEmpty())){
            eFNameLbl.setText("?");
            eLNameLbl.setText("?");
            eEmailLbl.setText("?");
            ePasswordLbl.setText("?");
            ePassConfLbl.setText("?");
            eNoticeLbl.setText("'?' shows the required fields");
        }else if(editFname.getText().trim().isEmpty()){
            eFNameLbl.setText("?");
            eLNameLbl.setText("");
            eEmailLbl.setText("");
            ePasswordLbl.setText("");
            ePassConfLbl.setText("");
            eNoticeLbl.setText("'?' shows the required fields");
        }else if(editLname.getText().trim().isEmpty()){
            eFNameLbl.setText("");
            eLNameLbl.setText("?");
            eEmailLbl.setText("");
            ePasswordLbl.setText("");
            ePassConfLbl.setText("");
            eNoticeLbl.setText("'?' shows the required fields");
        }else if(editEmail.getText().trim().isEmpty()){
            eFNameLbl.setText("");
            eLNameLbl.setText("");
            eEmailLbl.setText("?");
            ePasswordLbl.setText("");
            ePassConfLbl.setText("");
            eNoticeLbl.setText("'?' shows the required fields");
        }else if(editPassword.getText().trim().isEmpty()){
            eFNameLbl.setText("");
            eLNameLbl.setText("");
            eEmailLbl.setText("");
            ePasswordLbl.setText("?");
            ePassConfLbl.setText("");
            eNoticeLbl.setText("'?' shows the required fields");
        }else if(editPasswordConf.getText().trim().isEmpty()){
            eFNameLbl.setText("");
            eLNameLbl.setText("");
            eEmailLbl.setText("");
            ePasswordLbl.setText("");
            ePassConfLbl.setText("?");
            eNoticeLbl.setText("'?' shows the required fields");
        }else if(ValidateData.validateNames(editFname)=="Invalid"){
            eEmptySymbolRemover();
            JOptionPane.showMessageDialog(new JFrame(), "First Name is Invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(ValidateData.validateNames(editLname)=="Invalid"){
            eEmptySymbolRemover();
            JOptionPane.showMessageDialog(new JFrame(), "Last Name is Invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(ValidateData.validateEmail(editEmail)=="Invalid"){
            eEmptySymbolRemover();
            JOptionPane.showMessageDialog(new JFrame(), "Email is Invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(ValidateData.validatePassword(editPassword)=="Invalid"){
            eEmptySymbolRemover();
            JOptionPane.showMessageDialog(new JFrame(), "Your password must have 8 or more characters including at least one uppercase letter, one lowercase letter,"
                    + " one digit, and one special character for added security. Please re-enter your password ",
                    "Error", JOptionPane.ERROR_MESSAGE);
            editPassword.setText("");
            editPasswordConf.setText("");
        }else if(!(new String(editPassword.getPassword()).equals(new String(editPasswordConf.getPassword())))){
            eEmptySymbolRemover();
            JOptionPane.showMessageDialog(new JFrame(), "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            eEmptySymbolRemover();
            
            editFname.setText("");
            editLname.setText("");
            editEmail.setText("");
            editPassword.setText("");
            editPasswordConf.setText("");
            
            JOptionPane.showMessageDialog(this, "Your details have been edited Successfully!");
        }
            
        
    }
    
    private void editPassConfToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPassConfToggleButtonMouseClicked
        // TODO add your handling code here:
        if(editPassConfToggleButton.isSelected()){
            editPasswordConf.setEchoChar((char)0);
            editPassConfToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("eye-close-line.png")));
        }else{
            editPasswordConf.setEchoChar('\u25cf');
            editPassConfToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("eye-line.png")));
        }
    }//GEN-LAST:event_editPassConfToggleButtonMouseClicked

    private void editPassConfToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPassConfToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPassConfToggleButtonActionPerformed

    private void editPassToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPassToggleButtonMouseClicked
        // TODO add your handling code here:
        if(editPassToggleButton.isSelected()){
            editPassword.setEchoChar((char)0);
            editPassToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("eye-close-line.png")));
        }else{
            editPassword.setEchoChar('\u25cf');
            editPassToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("eye-line.png")));
        }
    }//GEN-LAST:event_editPassToggleButtonMouseClicked

    private void editPassToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPassToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPassToggleButtonActionPerformed

    private void eCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eCloseButtonMouseClicked
        dispose();
    }//GEN-LAST:event_eCloseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel eCloseButton;
    private javax.swing.JLabel eEmailLbl;
    private javax.swing.JLabel eFNameLbl;
    private javax.swing.JLabel eLNameLbl;
    private javax.swing.JLabel eNoticeLbl;
    private javax.swing.JLabel ePassConfLbl;
    private javax.swing.JLabel ePasswordLbl;
    private javax.swing.JTextField editEmail;
    private javax.swing.JTextField editFname;
    private javax.swing.JTextField editLname;
    private javax.swing.JToggleButton editPassConfToggleButton;
    private javax.swing.JToggleButton editPassToggleButton;
    private javax.swing.JPasswordField editPassword;
    private javax.swing.JPasswordField editPasswordConf;
    private javax.swing.JLabel fNameLbl;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lNameLbl;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel noticeLbl;
    private javax.swing.JToggleButton passConfToggleButton;
    private javax.swing.JToggleButton passToggleButton;
    private javax.swing.JButton saveEditBtn;
    private javax.swing.JButton signInRedirectButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField signUpEmail;
    private javax.swing.JLabel signUpEmailLbl;
    private javax.swing.JLabel signUpPassConfLbl;
    private javax.swing.JPasswordField signUpPassword;
    private javax.swing.JPasswordField signUpPasswordConf;
    private javax.swing.JLabel signUpPasswordLbl;
    // End of variables declaration//GEN-END:variables
}
