/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finanace_tracker;

/**
 *
 * @author Tharusha
 */
public class EditCurrency extends javax.swing.JFrame {

    /**
     * Creates new form EditCurrency
     */
    public EditCurrency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editCurrencyBtn = new javax.swing.JComboBox<>();
        currencySelectBtn = new javax.swing.JButton();
        eCurrCloseButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Currency");

        editCurrencyBtn.setBackground(new java.awt.Color(255, 255, 255));
        editCurrencyBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editCurrencyBtn.setForeground(new java.awt.Color(102, 0, 153));
        editCurrencyBtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sri Lankan Rupee (LKR)", "United States Dollar (USD)", "Euro (EUR)", "British Pound Sterling (GBP)", "Japanese Yen (JPY)", "Australian Dollar (AUD)", "Canadian Dollar (CAD)", "Swiss Franc (CHF)", "Chinese Yuan (CNY)", "Swedish Krona (SEK)", "New Zealand Dollar (NZD)", "Mexican Peso (MXN)", "Singapore Dollar (SGD)", "Hong Kong Dollar (HKD)", "Norwegian Krone (NOK)", "South Korean Won (KRW)", "Turkish Lira (TRY)", "Russian Ruble (RUB)", "Indian Rupee (INR)", "Brazilian Real (BRL)", "South African Rand (ZAR)", "Philippine Peso (PHP)", "Czech Koruna (CZK)", "Indonesian Rupiah (IDR)", "Malaysian Ringgit (MYR)", "Hungarian Forint (HUF)", "Icelandic Króna (ISK)", "Croatian Kuna (HRK)", "Bulgarian Lev (BGN)", "Romanian Leu (RON)", "Danish Krone (DKK)", "Thai Baht (THB)", "Polish Zloty (PLN)", "Israeli Shekel (ILS)", "Chilean Peso (CLP)", "Pakistani Rupee (PKR)", "Saudi Riyal (SAR)", "Argentine Peso (ARS)", "Colombian Peso (COP)", "Vietnamese Dong (VND)", "Peruvian Sol (PEN)" }));
        editCurrencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCurrencyBtnActionPerformed(evt);
            }
        });

        currencySelectBtn.setBackground(new java.awt.Color(255, 255, 255));
        currencySelectBtn.setForeground(new java.awt.Color(102, 0, 153));
        currencySelectBtn.setText("Select");
        currencySelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencySelectBtnActionPerformed(evt);
            }
        });

        eCurrCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross (2).png"))); // NOI18N
        eCurrCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eCurrCloseButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCurrencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(eCurrCloseButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(currencySelectBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eCurrCloseButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(editCurrencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(currencySelectBtn)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editCurrencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCurrencyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCurrencyBtnActionPerformed

    private void updateCurrencyEverywhere(String selectedCurrency) {
        // Logic to update currency across the application
        System.out.println("Currency selected: " + selectedCurrency);

        // Update UI components
        // For example, if you have a label showing the current currency:
        // currencyLabel.setText(selectedCurrency);

        // Notify other parts of the application
        // This might involve sending events, updating global state, etc.

        // Example:
        // ApplicationState.setCurrentCurrency(selectedCurrency);
        // ApplicationState.notifyCurrencyChanged();
    }

    
    private void currencySelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencySelectBtnActionPerformed
        // Get the selected currency
        String selectedCurrency = (String) editCurrencyBtn.getSelectedItem();

        // To update the currency across the application
        updateCurrencyEverywhere(selectedCurrency);
    }//GEN-LAST:event_currencySelectBtnActionPerformed

    private void eCurrCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eCurrCloseButtonMouseClicked
        dispose();
    }//GEN-LAST:event_eCurrCloseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCurrency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton currencySelectBtn;
    private javax.swing.JLabel eCurrCloseButton;
    private javax.swing.JComboBox<String> editCurrencyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
