/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finanace_tracker;
import java.awt.BorderLayout;
import javax.swing.JLayeredPane;


import javax.swing.JPanel;


/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_design1 = new javax.swing.JPanel();
        pnl_menu = new keeptoo.KGradientPanel();
        pnl_profile_info = new javax.swing.JPanel();
        lbl_pfp = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_accemail = new javax.swing.JLabel();
        btn_load_income = new javax.swing.JButton();
        btn_load_expenses = new javax.swing.JButton();
        btn_load_dashboard = new javax.swing.JButton();
        btn_load_goals = new javax.swing.JButton();
        btn_load_reports = new javax.swing.JButton();
        btn_load_signin = new javax.swing.JButton();
        btn_load_reports1 = new javax.swing.JButton();
        btn_load_signin1 = new javax.swing.JButton();
        btn_load_expenses1 = new javax.swing.JButton();
        mainPane = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_design1.setBackground(new java.awt.Color(0, 102, 102));
        pnl_design1.setForeground(new java.awt.Color(0, 102, 102));
        pnl_design1.setToolTipText("");

        pnl_menu.setkEndColor(new java.awt.Color(51, 0, 102));
        pnl_menu.setkGradientFocus(700);
        pnl_menu.setkStartColor(new java.awt.Color(85, 77, 222));

        pnl_profile_info.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pfp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_username.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(0, 0, 0));
        lbl_username.setText("User Name");

        lbl_accemail.setFont(new java.awt.Font("MS PGothic", 0, 10)); // NOI18N
        lbl_accemail.setForeground(new java.awt.Color(0, 0, 0));
        lbl_accemail.setText("user@email.com");

        javax.swing.GroupLayout pnl_profile_infoLayout = new javax.swing.GroupLayout(pnl_profile_info);
        pnl_profile_info.setLayout(pnl_profile_infoLayout);
        pnl_profile_infoLayout.setHorizontalGroup(
            pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))))
        );
        pnl_profile_infoLayout.setVerticalGroup(
            pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                .addGroup(pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbl_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_accemail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_profile_infoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_load_income.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_income.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_income.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_income.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cash.png"))); // NOI18N
        btn_load_income.setText("Incomes");
        btn_load_income.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_income.setBorderPainted(false);
        btn_load_income.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_income.setFocusPainted(false);
        btn_load_income.setFocusable(false);
        btn_load_income.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_income.setIconTextGap(25);
        btn_load_income.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_income.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_incomeActionPerformed(evt);
            }
        });

        btn_load_expenses.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_expenses.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_expenses.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/spending.png"))); // NOI18N
        btn_load_expenses.setText("Expenses");
        btn_load_expenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_expenses.setBorderPainted(false);
        btn_load_expenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_expenses.setFocusPainted(false);
        btn_load_expenses.setFocusable(false);
        btn_load_expenses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_expenses.setIconTextGap(25);
        btn_load_expenses.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_expenses.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_expensesActionPerformed(evt);
            }
        });

        btn_load_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_dashboard.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_dashboard.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dashboard (1).png"))); // NOI18N
        btn_load_dashboard.setText("Dashboard");
        btn_load_dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_dashboard.setBorderPainted(false);
        btn_load_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_dashboard.setFocusPainted(false);
        btn_load_dashboard.setFocusable(false);
        btn_load_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_dashboard.setIconTextGap(25);
        btn_load_dashboard.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_dashboard.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_dashboardActionPerformed(evt);
            }
        });

        btn_load_goals.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_goals.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_goals.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_goals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/goal.png"))); // NOI18N
        btn_load_goals.setText("Goals");
        btn_load_goals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_goals.setBorderPainted(false);
        btn_load_goals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_goals.setFocusPainted(false);
        btn_load_goals.setFocusable(false);
        btn_load_goals.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_goals.setIconTextGap(25);
        btn_load_goals.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_goals.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_goalsActionPerformed(evt);
            }
        });

        btn_load_reports.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_reports.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_reports.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/seo-report (1).png"))); // NOI18N
        btn_load_reports.setText("Reports");
        btn_load_reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_reports.setBorderPainted(false);
        btn_load_reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_reports.setFocusPainted(false);
        btn_load_reports.setFocusable(false);
        btn_load_reports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_reports.setIconTextGap(25);
        btn_load_reports.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_reports.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_reportsActionPerformed(evt);
            }
        });

        btn_load_signin.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_signin.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_signin.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout (1).png"))); // NOI18N
        btn_load_signin.setText("Log Out");
        btn_load_signin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_signin.setBorderPainted(false);
        btn_load_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_signin.setFocusPainted(false);
        btn_load_signin.setFocusable(false);
        btn_load_signin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_signin.setIconTextGap(25);
        btn_load_signin.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_signin.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_signinActionPerformed(evt);
            }
        });

        btn_load_reports1.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_reports1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_reports1.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_reports1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/budget.png"))); // NOI18N
        btn_load_reports1.setText("Calculator");
        btn_load_reports1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_reports1.setBorderPainted(false);
        btn_load_reports1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_reports1.setFocusPainted(false);
        btn_load_reports1.setFocusable(false);
        btn_load_reports1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_reports1.setIconTextGap(25);
        btn_load_reports1.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_reports1.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_reports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_reports1ActionPerformed(evt);
            }
        });

        btn_load_signin1.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_signin1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_signin1.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_signin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gear.png"))); // NOI18N
        btn_load_signin1.setText("Settings");
        btn_load_signin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_signin1.setBorderPainted(false);
        btn_load_signin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_signin1.setFocusPainted(false);
        btn_load_signin1.setFocusable(false);
        btn_load_signin1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_signin1.setIconTextGap(25);
        btn_load_signin1.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_signin1.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_signin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_signin1ActionPerformed(evt);
            }
        });

        btn_load_expenses1.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_expenses1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        btn_load_expenses1.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_expenses1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/earning.png"))); // NOI18N
        btn_load_expenses1.setText("Investments");
        btn_load_expenses1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_expenses1.setBorderPainted(false);
        btn_load_expenses1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_load_expenses1.setFocusPainted(false);
        btn_load_expenses1.setFocusable(false);
        btn_load_expenses1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_expenses1.setIconTextGap(25);
        btn_load_expenses1.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_expenses1.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_expenses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_expenses1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_load_signin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_reports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_income, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_expenses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_goals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_profile_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_reports1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_signin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_expenses1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addComponent(pnl_profile_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_load_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_income, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_expenses1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_reports1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btn_load_signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout pnl_design1Layout = new javax.swing.GroupLayout(pnl_design1);
        pnl_design1.setLayout(pnl_design1Layout);
        pnl_design1Layout.setHorizontalGroup(
            pnl_design1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_design1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnl_design1Layout.setVerticalGroup(
            pnl_design1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_design1Layout.createSequentialGroup()
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPane.setMaximumSize(new java.awt.Dimension(788, 600));
        mainPane.setPreferredSize(new java.awt.Dimension(788, 600));
        mainPane.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_design1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_design1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_load_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_incomeActionPerformed
          // Assuming pane_load_ui is a JPanel
        JLayeredPane pane_load_ui = new JLayeredPane();

        pane_load_ui.setLayout(new BorderLayout()); // Use BorderLayout or another layout manager of your choice

        // Assuming pnl is an instance of the Dashboard panel 
        Income pnl = new Income();
    
        // Add pnl to mainPane
        mainPane.removeAll(); // Remove all components from mainPane
        mainPane.add(pnl, BorderLayout.CENTER); // Add pnl to mainPane
        mainPane.revalidate(); // Revalidate the mainPane to reflect the changes
        mainPane.repaint(); // Repaint the mainPane to reflect the changes
    }//GEN-LAST:event_btn_load_incomeActionPerformed

    private void btn_load_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_expensesActionPerformed
        // Assuming pane_load_ui is a JPanel
        JLayeredPane pane_load_ui = new JLayeredPane();

        pane_load_ui.setLayout(new BorderLayout()); // Use BorderLayout or another layout manager of your choice

        // Assuming pnl is an instance of the Dashboard panel 
        Expenses pnl = new Expenses();
    
        // Add pnl to mainPane
        mainPane.removeAll(); // Remove all components from mainPane
        mainPane.add(pnl, BorderLayout.CENTER); // Add pnl to mainPane
        mainPane.revalidate(); // Revalidate the mainPane to reflect the changes
        mainPane.repaint(); // Repaint the mainPane to reflect the changes
    }//GEN-LAST:event_btn_load_expensesActionPerformed

    private void btn_load_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_dashboardActionPerformed
        // Assuming pane_load_ui is a JPanel
        JLayeredPane pane_load_ui = new JLayeredPane();

        pane_load_ui.setLayout(new BorderLayout()); // Use BorderLayout or another layout manager of your choice

        // Assuming pnl is an instance of the Dashboard panel 
        Dashboard pnl = new Dashboard();
    
        // Add pnl to mainPane
        mainPane.removeAll(); // Remove all components from mainPane
        mainPane.add(pnl, BorderLayout.CENTER); // Add pnl to mainPane
        mainPane.revalidate(); // Revalidate the mainPane to reflect the changes
        mainPane.repaint(); // Repaint the mainPane to reflect the changes
    }//GEN-LAST:event_btn_load_dashboardActionPerformed

    private void btn_load_goalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_goalsActionPerformed

    }//GEN-LAST:event_btn_load_goalsActionPerformed

    private void btn_load_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_reportsActionPerformed

    }//GEN-LAST:event_btn_load_reportsActionPerformed

    private void btn_load_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_signinActionPerformed

    }//GEN-LAST:event_btn_load_signinActionPerformed

    private void btn_load_reports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_reports1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_load_reports1ActionPerformed

    private void btn_load_signin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_signin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_load_signin1ActionPerformed

    private void btn_load_expenses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_expenses1ActionPerformed
         // Assuming pane_load_ui is a JPanel
        JLayeredPane pane_load_ui = new JLayeredPane();

        pane_load_ui.setLayout(new BorderLayout()); // Use BorderLayout or another layout manager of your choice

        // Assuming pnl is an instance of the Dashboard panel 
        Investments pnl = new Investments();
    
        // Add pnl to mainPane
        mainPane.removeAll(); // Remove all components from mainPane
        mainPane.add(pnl, BorderLayout.CENTER); // Add pnl to mainPane
        mainPane.revalidate(); // Revalidate the mainPane to reflect the changes
        mainPane.repaint(); // Repaint the mainPane to reflect the changes
    }//GEN-LAST:event_btn_load_expenses1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_load_dashboard;
    private javax.swing.JButton btn_load_expenses;
    private javax.swing.JButton btn_load_expenses1;
    private javax.swing.JButton btn_load_goals;
    private javax.swing.JButton btn_load_income;
    private javax.swing.JButton btn_load_reports;
    private javax.swing.JButton btn_load_reports1;
    private javax.swing.JButton btn_load_signin;
    private javax.swing.JButton btn_load_signin1;
    private javax.swing.JLabel lbl_accemail;
    private javax.swing.JLabel lbl_pfp;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLayeredPane mainPane;
    private javax.swing.JPanel pnl_design1;
    private keeptoo.KGradientPanel pnl_menu;
    private javax.swing.JPanel pnl_profile_info;
    // End of variables declaration//GEN-END:variables
}
